version: '3'
services:
  app:
    build : .
    ports:
      - 9191:9191
    networks:
      - microserviceproducer_kafka-net
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/app_db
      - SPRING_DATASOURCE_USERNAME=app_user
      - SPRING_DATASOURCE_PASSWORD=app_pass
      - KAFKA_BROKER=kafka1:9092
      - ZOOKEEPER_HOST=zookeeper1:2182
      - SPRING_KAFKA_TOPIC=ORDER_TOPIC

  postgres:
    image: postgres
    container_name: postgres1
    ports:
      - 5432:5432
    networks:
      - microserviceproducer_kafka-net
    volumes:
      - postgres-data:/data/db
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_pass

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin1
    ports:
      - 5050:80
    networks:
      - microserviceproducer_kafka-net
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin_pass



volumes:
  postgres-data:

networks:
  microserviceproducer_kafka-net:
   external: true
