spring:
  kafka:
    consumer:
      group-id: foo
      auto-offset-reset: latest
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      bootstrap-servers: kafka:9092
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/app_db}
    username: ${SPRING_DATASOURCE_USERNAME:app_user}
    password: ${SPRING_DATASOURCE_PASSWORD:app_pass}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
auto:
  create:
    topics:
      enable: 'true'
app:
  kafka:
    topic: ${SPRING_KAFKA_TOPIC:ORDER_TOPIC}
server:
  port: '9191'
